# Generated by Django 5.2 on 2025-05-08 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('alarm_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('video_path', models.CharField(max_length=500)),
                ('image_path', models.CharField(blank=True, max_length=500, null=True)),
                ('desc', models.CharField(max_length=255)),
                ('state', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Behavior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='算法编号')),
                ('name', models.CharField(max_length=100, verbose_name='算法名称')),
                ('interval', models.IntegerField(default=10, verbose_name='检测间隔')),
                ('sensitivity', models.FloatField(default=0.5, verbose_name='灵敏度')),
                ('overlap_thresh', models.FloatField(default=0.45, verbose_name='阈值')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '算法',
                'verbose_name_plural': '算法',
                'db_table': 'av_behavior',
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.IntegerField(verbose_name='排序')),
                ('code', models.CharField(max_length=50, verbose_name='摄像头编号')),
                ('name', models.CharField(max_length=100, verbose_name='摄像头名称')),
                ('stream_name', models.CharField(max_length=200, verbose_name='视频流名称')),
                ('stream_state', models.BooleanField(verbose_name='视频流状态')),
                ('state', models.BooleanField(verbose_name='状态')),
                ('remark', models.CharField(max_length=200, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '摄像头',
                'verbose_name_plural': '摄像头',
                'db_table': 'av_camera',
            },
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('user_id', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_name', models.CharField(default='gemma-3-4b', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户')),
                ('sort', models.IntegerField(verbose_name='排序')),
                ('code', models.CharField(max_length=50, verbose_name='编号')),
                ('stream_app', models.CharField(max_length=50, verbose_name='视频流应用')),
                ('stream_name', models.CharField(max_length=100, verbose_name='视频流名称')),
                ('stream_video', models.CharField(max_length=100, verbose_name='视频流视频')),
                ('stream_audio', models.CharField(max_length=100, verbose_name='视频流音频')),
                ('behavior_code', models.CharField(max_length=50, verbose_name='算法行为编号')),
                ('interval', models.IntegerField(verbose_name='检测间隔')),
                ('sensitivity', models.IntegerField(verbose_name='灵敏度')),
                ('overlap_thresh', models.IntegerField(verbose_name='阈值')),
                ('remark', models.CharField(max_length=200, verbose_name='备注')),
                ('push_stream', models.BooleanField(verbose_name='是否推流')),
                ('push_stream_app', models.CharField(max_length=50, null=True, verbose_name='推流应用')),
                ('push_stream_name', models.CharField(max_length=100, null=True, verbose_name='推流名称')),
                ('state', models.IntegerField(default=0, verbose_name='布控状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '布控',
                'verbose_name_plural': '布控',
                'db_table': 'av_control',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.IntegerField(verbose_name='排序')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.CharField(max_length=200, verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('state', models.IntegerField(verbose_name='状态')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'db_table': 'av_notification',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('image_data', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app.chathistory')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
