# Generated by Django 5.2 on 2025-05-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_behavior_options_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alarm',
            options={'ordering': ['-create_time'], 'verbose_name': '告警', 'verbose_name_plural': '告警'},
        ),
        migrations.AddField(
            model_name='alarm',
            name='video_absolute_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='视频绝对路径'),
        ),
    ]
